### PR TITLE
Replace base_resolution with width/height fields

### PR DESCRIPTION
**Pull request by phr00t**
CogVideoX-Fun claims it can do videos at any resolution, so it didn't sit right with me that this wrapper forced you into a few obscure "base resolution" selections. In my fork, I've replaced the picker with just simple width/height fields which makes the node more flexible. Here is the pull request if you choose to do the same!

image

Works good! Example above is getting width/height from the image (I converted them to inputs, they default as widgets).

### CODE REVIEW

**Comment by kijai** [comment]
The base resolution stuff comes from their original code, I don't really know how important it is, but they spent quite a bit of code to make sure the resolution matches their predefined ones.

**Comment by phr00t** [comment]
> The base resolution stuff comes from their original code, I don't really know how important it is, but they spent quite a bit of code to make sure the resolution matches their predefined ones.

I was really struggling when my videos were being downsized unexpectedly, but the next bump up was too slow to generate... With this change, I have more control over the resolution and have gotten better results at acceptable speeds. I consider it a significant improvement but understand if you want to keep things from their original code.

**Comment by phr00t** [comment]
@kijai just a heads up: I added LCM and UniPC schedulers to the CogVideoXFun sampler, and LCM so far seems pretty solid at lower steps, but I haven't tested much. UniPC works too, but LCM seemed better. You can cherry pick this commit if you want to bring it in:

https://github.com/kijai/ComfyUI-CogVideoXWrapper/pull/71/commits/df3f21028700c5a3e3f768958d8660d341efb1a1

**Comment by kijai** [comment]
Yeah thanks, should test those more, `SASolverScheduler `also seems to work well.

**Pull request closed without merging**
